CRUD User
hobathanh/APIBook pull request #4
Opened 2023-03-06 09:37 UTC by hobathanh

- Format code (Migration file)
- CRUD User
- Write unit tests for each file

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/error/UserAvailableException.java
> +public class UserAvailableException extends DomainException {
e có thể dùng class name này: `UserAlreadyExistException`

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntity.java
> +    public static final String ID_FIELD = "id";
xóa dòng này nếu ko dùng e

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
xóa dòng trống này e

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
xóa bớt dòng trống này e

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
xóa dòng trống này e

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserRepository.java
> +    @Query("SELECT u from UserEntity u where u.username = :username")
Xóa dòng này nếu ko cần thiết e?

2023-03-06 15:17 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +
xóa bớt dòng trống này e

2023-03-06 15:17 UTC, tleviet commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
>      firstName VARCHAR(255),
tên column ở sql nên là `first_name` hoặc `firstname` e. Tương tự với `last_name` hoặc `lastname`.

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/APIBookApplicationTests.java
> +        System.out.println("###### environment: " + String.join(", ", environment.getActiveProfiles()));
Xóa System print trong code e

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL))
e có thể remove `this.` phía trước biến `mvc` nhé

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +//        verify(userService).createUser(user);
sao comment dòng này e?

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +//        verify(userService).updateUser(user.getId(), updatedUser);
sao comment dòng này e?

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void findUserById_Throw() {
update tên method cho clear e: `_Throw` gì e?

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void createUser_WithExistingUser() {
update method name dùng `..._Throw...` như ở test trên cho đồng bộ e

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +                .thenReturn(Optional.of(user));
dòng code này ngắn ko cần xuống hàng cũng đc e

2023-03-06 15:17 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void deleteUser_Throw() {
method này `_Throw` gì e?

2023-03-06 16:05 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +
resolved

2023-03-06 16:06 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +
resolved

2023-03-06 16:11 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO CreateUser(@RequestBody User user) {
resolved

2023-03-06 16:11 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO UpdateUser(@PathVariable UUID id, @RequestBody UserDTO userDTO) {
resolved

2023-03-06 16:11 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserDTO.java
> +
resolved

2023-03-06 16:13 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/error/UserAvailableException.java
> +public class UserAvailableException extends DomainException {
resolved

2023-03-06 16:14 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntity.java
> +    public static final String ID_FIELD = "id";
resolved

2023-03-06 16:14 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
resolved

2023-03-06 16:15 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
resolved

2023-03-06 16:16 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntityMapper.java
> +
resolved

2023-03-06 16:17 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO CreateUser(@RequestBody User user) {
Thiếu final cho param

2023-03-06 16:17 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO UpdateUser(@PathVariable UUID id, @RequestBody UserDTO userDTO) {
+final

2023-03-06 16:17 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public void DeleteUser(@PathVariable UUID id) {
final

2023-03-06 16:18 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserDTOMapper.java
> +                .password(user.getPassword())
Thực sự là muốn response password về frontend?

2023-03-06 16:19 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    public User findUserById(final UUID id) {
```suggestion
    public User findById(final UUID id) {
```

2023-03-06 16:19 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    private void verifyUserAvailable(final User user) {
```suggestion
    private void verifyUsernameAvailable(final String username) {
```

2023-03-06 16:19 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        final Optional<User> userOptional = userStore.findUserByUserName(user.getUsername());
Tại sao lúc là `UserName` lúc là `Username`?

2023-03-06 16:20 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new UserAvailableException("User Available!");
```suggestion
            throw new UserAvailableException("User Available!");
```

Message không phù hợp

2023-03-06 16:24 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/error/UserAvailableException.java
> +        super(HttpStatus.CONFLICT, message, args);
```suggestion
        super(HttpStatus.BAD_REQUEST, message, args);
```

2023-03-06 16:27 UTC, voquanghoa commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    enabled   BOOLEAN      NOT NULL,
thêm constrains cho username không được trùng

2023-03-06 16:28 UTC, voquanghoa commented on src/main/resources/db/migration/DEV/V1_0_0_020320231647__create_sample.sql
> +        '2023-03-02 12:02:00', '2023-03-02 12:02:00', 'image_Book2.jpg',
với những PR sau, tuyệt đối 1 sửa file migration. Muốn thay đổi trong db, luôn tạo file migration mới

2023-03-06 16:29 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +    void createUser_Ok() throws Exception {
```suggestion
    void createUser_OK() throws Exception {
```

2023-03-06 16:32 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(expected.getRoleId().toString(), actual.getRoleId().toString());
```suggestion
        assertEquals(expected.getRoleId(), actual.getRoleId());
```

2023-03-06 16:32 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(userEntity.getRoleId().toString(), actual.getRoleId().toString());
```suggestion
        assertEquals(userEntity.getRoleId(), actual.getRoleId());
```

2023-03-06 17:57 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserRepository.java
> +    @Query("SELECT u from UserEntity u where u.username = :username")
resolved

2023-03-06 17:57 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +
resolved

2023-03-06 17:57 UTC, hobathanh commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
>      firstName VARCHAR(255),
resolved

2023-03-06 17:57 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/APIBookApplicationTests.java
> +        System.out.println("###### environment: " + String.join(", ", environment.getActiveProfiles()));
resolved

2023-03-06 17:57 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL))
resolved

2023-03-06 17:57 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +//        verify(userService).createUser(user);
resolved, e chưa kịp chỉnh lại ạ

2023-03-06 17:58 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +//        verify(userService).updateUser(user.getId(), updatedUser);
resolved

2023-03-06 17:59 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void findUserById_Throw() {
resolved

2023-03-06 17:59 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void createUser_WithExistingUser() {
resolved

2023-03-06 17:59 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +                .thenReturn(Optional.of(user));
resolved

2023-03-06 18:00 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void deleteUser_Throw() {
resolved

2023-03-06 18:00 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO CreateUser(@RequestBody User user) {
resolved

2023-03-06 18:00 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO UpdateUser(@PathVariable UUID id, @RequestBody UserDTO userDTO) {
resolved

2023-03-06 18:00 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    public List<User> findAllUsers() {
resolved

2023-03-06 18:01 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserDTOMapper.java
> +                .password(user.getPassword())
phần xử lý pw e chưa làm a, để e làm ạ

2023-03-06 18:01 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        final Optional<User> userOptional = userStore.findUserByUserName(user.getUsername());
resolved

2023-03-06 18:01 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new UserAvailableException("User Available!");
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/error/UserAvailableException.java
> +        super(HttpStatus.CONFLICT, message, args);
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    enabled   BOOLEAN      NOT NULL,
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/main/resources/db/migration/DEV/V1_0_0_020320231647__create_sample.sql
> +        '2023-03-02 12:02:00', '2023-03-02 12:02:00', 'image_Book2.jpg',
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +    void createUser_Ok() throws Exception {
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(expected.getRoleId().toString(), actual.getRoleId().toString());
resolved

2023-03-06 18:02 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(userEntity.getRoleId().toString(), actual.getRoleId().toString());
resolved

2023-03-07 04:01 UTC, nguyenvanman requested changes

2023-03-07 04:01 UTC, nguyenvanman commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    firstname VARCHAR(255),
```suggestion
    first_name VARCHAR(255),
```

2023-03-07 04:01 UTC, nguyenvanman commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    lastname  VARCHAR(255),
```suggestion
    last_name  VARCHAR(255),
```

2023-03-07 09:55 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +
resolved

2023-03-07 09:55 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        verifyUserAvailable(user);
resolved

2023-03-07 09:55 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        user.setUsername(updatedUser.getUsername());
resolved

2023-03-07 09:55 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/user/UserDTOMapper.java
> +                .password(user.getPassword())
resolved

2023-03-07 09:55 UTC, hobathanh commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    firstname VARCHAR(255),
resolved

2023-03-07 09:55 UTC, hobathanh commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +    lastname  VARCHAR(255),
resolved

2023-03-07 12:22 UTC, tleviet commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        final var userOpt = Optional.of(user);
tên biến nên đặt rõ hơn e `..Opt` đặt userOptional lun e

2023-03-07 12:22 UTC, tleviet commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(expected.size(), userStore.findAllUsers().size());
sao when xong lại đến assertEquals lun e, nên có dòng `userStore.findAllUsers()` trước assertEquals chứ e

2023-03-07 12:22 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void deleteUser_ThrowEmptyId() {
`ThrowEmptyId` :thinking:, throw exception gì chứ e (a thấy có test này mà `createUser_ThrowUserAlreadyExist`)

2023-03-07 12:22 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +
xóa bớt dòng trống ko cần thiết e, xem mấy chỗ khác xóa lun e hỉ

2023-03-08 06:29 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +
resolved

2023-03-08 06:29 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +    void deleteUser_ThrowEmptyId() {
resolved

2023-03-08 06:29 UTC, hobathanh commented on src/test/java/com/bathanh/apibook/persistence/user/UserStoreTest.java
> +        assertEquals(expected.size(), userStore.findAllUsers().size());
resolved

2023-03-08 06:30 UTC, hobathanh commented on src/main/resources/db/migration/COMMON/V1_0_0_020320231323__create_table_users.sql
> +EXTENSION IF NOT EXISTS "uuid-ossp";
resolved, vâng a

2023-03-08 06:30 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public List<User> searchUsers(final String keyWord) {
resolved

2023-03-08 06:30 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new PropertyInputNotFoundException("Property input not found");
resolved

2023-03-08 06:31 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    private void verifyPropertyInput(final User user) {
resolved

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public List<UserDTO> findAllUsers() {
```suggestion
    public List<UserDTO> findAll() {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO createUser(final @RequestBody User user) {
```suggestion
    public UserDTO create(final @RequestBody User user) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +        return toUserDTO(userService.createUser(user));
```suggestion
        return toUserDTO(userService.create(user));
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public UserDTO updateUser(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
```suggestion
    public UserDTO update(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +        return toUserDTO(userService.updateUser(id, toUser(userDTO)));
```suggestion
        return toUserDTO(userService.update(id, toUser(userDTO)));
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserController.java
> +    public void deleteUser(final @PathVariable UUID id) {
```suggestion
    public void delete(final @PathVariable UUID id) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserDTO.java
> +    private String password;
Không được để field password này về client

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserDTO.java
> +    private String firstname;
```suggestion
    private String firstName;
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/user/UserDTO.java
> +    private String lastname;
```suggestion
    private String lastName;
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/User.java
> +    private String firstname;
```suggestion
    private String firstName;
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/User.java
> +    private String lastname;
```suggestion
    private String lastName;
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    public List<User> searchUsers(String keyword) {
```suggestion
    public List<User> search(final String keyword) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        return userStore.searchUsers(keyword);
```suggestion
        return userStore.search(keyword);
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    public User createUser(final User user) {
```suggestion
    public User create(final User user) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        user.setUsername(updatedUser.getUsername());
Ví dụ hệ thống có user1 và user2 và user2 đổi tên thành user1 thì sao

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        user.setPassword(updatedUser.getPassword());
Frontend có thể chỉ update user mà không đổi mật khẩu được không

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +    public User updateUser(final UUID id, final User updatedUser) {
```suggestion
    public User update(final UUID id, final User user) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new BadRequestException("Request failed, please check Password");
User luôn phải nhập mật khẩu khi cập nhật thông tin?

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        if (user.getUsername() == null) {
dùng isNotBlank trong StringUtils

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        if (user.getPassword() == null) {
Check tối thiểu 6 ký tự

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new BadRequestException("Request failed, please check Username");
Cần rõ hơn lỗi gì. Tại sao Username viết hoa

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +            throw new BadRequestException("Request failed, please check Password");
Cần rõ hơn lỗi gì. Tại sao Password viết hoa

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserEntity.java
> +    @Column(name = "last_name")
Mấy annotation không cần thiết, có thể xoá đi

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserRepository.java
> +    List<UserEntity> findAllByFirstnameContainingOrLastnameContainingOrUsernameContaining(final String firstname, final String lastname, final String username);
firstname, lastname không phải là từ ngữ đúng chính tả
![image](https://user-images.githubusercontent.com/10450325/223647643-7ffc0872-6e77-4a10-a91e-faeddd66f421.png)

username thì OK

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public List<User> findAllUsers() {
```suggestion
    public List<User> findAll() {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +                .stream().map(UserEntityMapper::toUser).collect(Collectors.toList());
```suggestion
                .stream().map(UserEntityMapper::toUser).collect(toList());
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public void deleteUser(final UUID id) {
```suggestion
    public void delete(final UUID id) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public User updateUser(final User updatedUser) {
```suggestion
    public User update(final User updatedUser) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public User createUser(final User user) {
```suggestion
    public User create(final User user) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public Optional<User> findUserById(final UUID uuid) {
```suggestion
    public Optional<User> findById(final UUID id) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserStore.java
> +    public Optional<User> findUserByUsername(final String username) {
```suggestion
    public Optional<User> findByUsername(final String username) {
```

2023-03-08 07:27 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +        mvc.perform(MockMvcRequestBuilders.delete(BASE_URL + "/" + id))
Cái này work nhưng không rõ tại sao nó có thể response OK. Thêm vào

```java
doNothing().when(userService).deleteUser(id);
```

2023-03-08 07:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/user/UserRepository.java
> +    List<UserEntity> findAllByFirstnameContainingOrLastnameContainingOrUsernameContaining(final String firstname, final String lastname, final String username);
Hàm quá dài, có thể đổi tên cho ngắn gọn hơn và dùng `@Query(....)` để chỉ định câu lệnh sql

2023-03-09 02:05 UTC, tleviet commented on src/test/java/com/bathanh/apibook/api/user/UserControllerTest.java
> +        final var actual = userService.search(user.getUsername());
xoá dòng nj nếu ko cần thiết e?

2023-03-09 02:05 UTC, tleviet commented on src/test/java/com/bathanh/apibook/domain/user/UserServiceTest.java
> +        assertThrows(UserAlreadyExistException.class, () -> userService.create(user));
thêm dòng trống phía dưới để tách assertThrows với verify e, xem chỗ khác update lun e hỉ

2023-03-09 02:14 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserValidation.java
> +        validatePasswordNotEmpty(user.getPassword());
a ơi, a Hòa bảo là trong TH create thì không được phép null pw, còn update thì được cho nên e mới tách ra làm 2 hàm validate pw á a

2023-03-09 02:15 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/error/UserAlreadyExistException.java
> +        super(HttpStatus.BAD_REQUEST, message, args);
e mới đổi từ conflict thành bad_request theo ý a Hòa bảo ạ

2023-03-09 02:33 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/user/UserValidation.java
> +            throw new BadRequestException("Request failed, password length must be at least 6 characters");
xoá `Request failed, ` ở phía trước đi e, sửa những chỗ khác lun e hỉ

2023-03-09 02:33 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/user/UserValidation.java
> +    private static void validatePasswordNotEmpty(final String password) {
method này mình check length của password đúng ko e? vậy e sửa lại method lun hỉ

2023-03-09 02:33 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/user/UserValidation.java
> +        validatePasswordNotEmpty(user.getPassword());
ok e

2023-03-09 15:29 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        if (!(user.getUsername().equals(updatedUser.getUsername()))) {
- [ ] chỗ này username = null thì sao e?

2023-03-09 15:38 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        if (!(user.getUsername().equals(updatedUser.getUsername()))) {
ở hàm validateUpdateUser(user) e đã kiểm tra TH username là null r throw ra lỗi r a. Cho nên sau khi thực hiện hàm đó thì TH username = null là đã check r , nên sau đó e kiểm tra user name mới này có khác username của userupdate không thôi. Nếu khác thì e update mới, còn không thì e k gán( tức vẫn lấy username cũ a)

2023-03-09 16:38 UTC, tleviet approved these changes

2023-03-09 16:38 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/user/UserService.java
> +        if (!(user.getUsername().equals(updatedUser.getUsername()))) {
Ah, ok e

2023-03-09 16:49 UTC, merged