add fetch book other api
hobathanh/APIBook pull request #9
Opened 2023-04-04 04:29 UTC by hobathanh

● Create migration to add the new columns in the book table

- subtitle

- publisher

- isbn13 (create index with unique)

- price

- year

- rating

● Update existing entity, service, controllers … to support the new columns
● Create migration to add a user name with user id is hardcode and name is
CRON_JOB and role is CONTRIBUTOR
● Create a bean with WebClient and config the base url
● Create BookItemDTO to match the response from given API
● Create an adapter to call the web API
● Create a mapper to convert the BookItemDTO to our Book
● Create a service to

- Call the adapter to get the Book Items

- Check the book if not existing from our db (check by isbn13)

- Convert to our book

- Store the new books to db with userId from the user above

● Create a cron job to run each hour to trigger the service
● Create a visualize on POSTMAN to show the books

2023-04-04 06:45 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/BookApiAdapter.java
> +    public BookItemDetailDTO fetchBookDetail(final String isbn13) {
Cứ để isbn13 đi

2023-04-04 06:50 UTC, voquanghoa commented on src/main/resources/db/migration/COMMON/V1_0_0_270320230944__update_table_books.sql
> +    ADD COLUMN price VARCHAR(20),
price là string vì còn có đơn vị tiền tệ

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/configuration/WebClientConfiguration.java
> +                .baseUrl("https://api.itbook.store/1.0")
Đưa cái url này vào vào application.properties

```
itbook.base-url=https://api.itbook.store/1.0
```

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/BookApiAdapter.java
> +        }
Thực tế cái này sẽ không bao giờ null nên không cần check đoạn này đâu

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/BookApiAdapter.java
> +        BooksResponseDTO response = webClient.get()
```suggestion
        final BooksResponseDTO response = webClient.get()
```

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/ScheduledTask.java
> +            logger.info("Scheduler has been started");
thêm return vào chứ

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/ScheduledTask.java
> +        bookService.storeNewBooks();
Đặt khối này vào lệnh try - catch

```suggestion
try{
       log("Start retrieving new books");
        bookService.storeNewBooks();
        log("Retrieving new books done");
} catch(Exception ex) {
       Logger.error("Failed to retrieve new book with error", ex);
   
}
```

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/error/FetchBookException.java
> +public class FetchBookException extends ResponseStatusException {
Không cần cái này đâu

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/book/BookEntity.java
> +    private Double rating;
Cái này tương tự trên nha

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/persistence/book/BookRepository.java
> +    @Query(value = "SELECT * FROM books WHERE isbn13 = :isbn13", nativeQuery = true)
Chỗ Query này có vẻ không cần thiết

2023-04-04 07:36 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/domain/book/BookValidationTest.java
> +        book.setPrice(null);
Cố gắng dùng các mệnh đề with

2023-04-04 07:36 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/fetchbook/ScheduledTask.java
> +    private static final Logger logger = LoggerFactory.getLogger(ScheduledTask.class);
Xem cách sử dụng `@Slf4j`

2023-04-04 08:23 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/persistence/book/BookEntity.java
> +    private Double rating;
e chưa hiểu ý của a, là 2 trường này mình chuyển về String à a @voquanghoa

2023-04-04 10:29 UTC, nguyenvanman requested changes

2023-04-04 10:29 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        List<BookItemDTO> newBooksToInsert = new ArrayList<>();
use Collection.filter

2023-04-04 10:29 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +            Book book = BookMapper.toBookFromItemDetail(bookDetail);
use static import

2023-04-04 10:29 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +            BookItemDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
```suggestion
            final BookItemDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
```

2023-04-04 10:29 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +            bookStore.create(book);
add to an array then call bookStore.saveAll(...)

2023-04-04 10:29 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/fetchbook/BookApiAdapter.java
> +package com.bathanh.apibook.domain.fetchbook;
Can put this file at integration layer

2023-04-04 10:55 UTC, tleviet commented on src/main/java/com/bathanh/apibook/api/fetchbook/BookItemDTO.java
> +public class BookItemDTO {
- [ ] bỏ class này vào chung package `api.book` lun e

2023-04-04 10:55 UTC, tleviet commented on src/main/java/com/bathanh/apibook/api/fetchbook/BookItemDetailDTO.java
> +public class BookItemDetailDTO {
- [ ] bỏ class này vào chung package `api.book` lun e, tương tự các class khác, xóa package `fetchbook` cho gọn e

2023-04-04 10:55 UTC, tleviet commented on src/main/java/com/bathanh/apibook/persistence/book/BookRepository.java
>      List<BookEntity> find(final String keyword);
- [ ] function find keyword nj chắc update thêm find với field mới lun e :thinking: 
cc @voquanghoa

2023-04-04 10:55 UTC, tleviet commented on src/main/resources/db/migration/COMMON/V1_0_0_270320230944__update_table_books.sql
> +    ADD COLUMN price VARCHAR(20),
ok, dạng số thì sau có tính toán chi dễ hơn, tạm thời để string cũng đc e

2023-04-04 10:55 UTC, tleviet commented on src/test/java/com/bathanh/apibook/api/fetchbook/BookMapperTest.java
> +
- [ ] xóa bớt dòng trống e

2023-04-04 11:08 UTC, tleviet commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +    private final BookRepository bookRepository;
- [ ] có bookStore ở đây rồi, remove bookRepository lun e

2023-04-05 06:37 UTC, nguyenvanman requested changes

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/integration/BookApiAdapter.java
> +package com.bathanh.apibook.domain.integration;
integration cùng level với domain, không phải ở trong domain

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/integration/BookApiAdapter.java
> +        final BookItemDetailDTO response = webClient.get()
```suggestion
        return webClient.get()
```

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +        List<BookItemDTO> newBooksToInsert = newBooks.stream()
```suggestion
        return newBooks.stream()
```

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/resources/application.properties
> +userIdCronJob=6302a41b-e61f-40a9-9dd0-9eb10028a749
```suggestion
user-id-cron-job=6302a41b-e61f-40a9-9dd0-9eb10028a749
```

2023-04-05 06:37 UTC, nguyenvanman commented on src/main/resources/application.properties
> +itbook.base-url=https://api.itbook.store/1.0
```suggestion
integration.itbook.base-url=https://api.itbook.store/1.0
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/book/BookController.java
> +    @GetMapping("isbn13")
```suggestion
    @GetMapping("isbn13/{isbn13}")
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/book/BookItemDTO.java
> +@NoArgsConstructor
Nó có empty constructor sẵn rồi nên không cần nữa

```suggestion
@NoArgsConstructor
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        return bookStore.findById(id).orElseThrow(supplyBookNotFound(id));
```suggestion
        return bookStore.findById(id).orElseThrow(supplyBookNotFoundById(id));
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +                .orElseThrow(supplyBookNotFoundIsbn13(isbn13));
```suggestion
                .orElseThrow(supplyBookNotFoundByIsbn13(isbn13));
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        verifyTitleAndAuthorAvailable(book.getTitle(), book.getAuthor());
Bỏ cái này đi cũng được

```suggestion
```

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +    private List<BookItemDTO> filterNewBooks(List<BookItemDTO> newBooks) {
Hàm private thì viết để phía dưới

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +        List<Book> existingBooks = bookStore.findAll();
Thiếu nhiều final

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +            bookService.verifyIsbn13BookAvailable(book);
Tại sao phải cần cái này

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/integration/ItBookService.java
> +            bookList.add(book);
stream --> map

2023-04-05 06:51 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/fakes/BookFakes.java
> +                .subtitle(RandomStringUtils.randomAlphabetic(3, 10))
static import

2023-04-05 06:51 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/fakes/BookFakes.java
> +    static final double rating = new SecureRandom().nextDouble() * 5.0;
viết thành hàm

2023-04-05 06:51 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var isbn13 = RandomStringUtils.randomNumeric(13);
static import

2023-04-05 06:51 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +                .orElseThrow(supplyBookNotFoundIsbn13(isbn13));
Hoặc
```
supplyBookNotFound("isbn13", isbn13);
```

và dùng chung cho id

2023-04-05 09:25 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        verifyIsbn13BookAvailable(book);
Nếu mình update 1 sách và KHÔNG thay đổi isbn13 của nó thì chỗ này sẽ throw lỗi

2023-04-05 09:27 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +        final List<Book> existingBooks = bookStore.findAll();
```suggestion
        final Set<String> existingIsbn13s = bookStore.findAll().map(....)...
```

2023-04-05 09:28 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/domain/book/BookServiceTest.java
> +        final var isbn13 = RandomStringUtils.randomNumeric(13);
static import

2023-04-05 09:31 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/api/book/BookItemDetailDTO.java
> +public class BookItemDetailDTO {
Mình không dùng chung class này cho cả api lâu nay và itbook nha. Bên ITBook nên sửa thành `ItBookItemDTO` và `ItBookDetailDTO`

2023-04-05 10:16 UTC, nguyenvanman requested changes

2023-04-05 10:16 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookValidation.java
> +        if (book.getYear() < 1800 || book.getYear() > 2023) {
Lấy năm hiện tại

2023-04-05 10:16 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookValidation.java
> +            book.setRating(0.0);
chỗ này là validate, chỉ validate, không set value ở đây

2023-04-05 10:26 UTC, nguyenhoanganhtuan1206 commented on src/test/java/com/bathanh/apibook/fakes/JwtFakes.java
> +        Set<GrantedAuthority> authorities = new HashSet<>();
final

2023-04-05 15:40 UTC, tleviet commented on src/main/java/com/bathanh/apibook/api/book/BookController.java
> +    public BookResponseDTO findByIsbn13(final @PathVariable String isbn13) {
- [ ] e có thể dùng RequestParam cho isbn13 nhé
- [ ] Mình không thể dùng chung api /find ah e? cc @voquanghoa

2023-04-05 17:22 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/api/book/BookController.java
> +    public BookResponseDTO findByIsbn13(final @PathVariable String isbn13) {
resolved

2023-04-06 02:41 UTC, tleviet commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                    final ItBookDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
- [ ] mình fetch books 2 lần lun hả e 🤔 ?
cc @voquanghoa

2023-04-06 03:02 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                    final ItBookDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
Cái đầu là list, cái sau là fetch detail

2023-04-06 03:02 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                    final ItBookDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
vâng a, tại vì 1 api không thể mô tả hết chi tiết của 1 book, nên e fetch 2 lần (lần đầu là để lấy isbn13 sau khi có isbn13 thì mình dùng api thứ 2 để lấy mô tả chi tiết của từng book (rating, year, ...) á a

2023-04-06 03:40 UTC, nguyenvanman requested changes

2023-04-06 03:40 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        final Optional<Book> bookOptional = bookStore.findBookByIsbn13(book.getIsbn13());
```suggestion
      bookStore.findBookByIsbn13(book.getIsbn13())
          .ifPresent(() -> throw ....);
```

2023-04-06 03:40 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        if (bookOptional.isPresent()) {
to remove

2023-04-06 03:40 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                    final ItBookDetailDTO bookDetail = bookApiAdapter.fetchBookDetail(bookToInsert.getIsbn13());
extract block này ra 1 hàm mới

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/domain/auths/JwtTokenServiceTest.java
> +        assertEquals("ROLE_USER", claims.get("roles").toString());
sao lại assert cái claims?

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/domain/book/BookValidationTest.java
> +        validate(book);
assert does not throw

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var expected = bookOptional.get();
expected = book, no?

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var actual = bookStore.saveAll(toBooks(expected));
không xài toBooks ở đây, tạo fakes

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var expected = buildBookEntities();
Cái này không mang ý nghĩa là expected

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var expected = buildBookEntities();
```suggestion
        final var bookEntities = buildBookEntities();
```

2023-04-06 03:40 UTC, nguyenvanman commented on src/test/java/com/bathanh/apibook/persistence/book/BookStoreTest.java
> +        final var actual = bookStore.save(toBook(bookSave));
không dùng toBook ở đây, tạo fakes

2023-04-06 05:14 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +    private Book createBookFromDetailDTO(final ItBookDetailDTO bookDetail) {
```suggestion
    private Book save(final ItBookDetailDTO itBookDetailDTO) {
```

2023-04-06 05:14 UTC, voquanghoa commented on src/test/java/com/bathanh/apibook/fakes/BookFakes.java
> +                .updatedAt(parse("2023-03-15T11:06:00.123456Z"))
Instant.now()

2023-04-06 06:31 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                .toList();
```suggestion
        final List<Book> bookList = booksToInsert.stream()
                .map(ItBookItemDTO::getIsbn13)
                .map(bookApiAdapter::fetchBookDetail)
                .map(this::save)
                .toList();
```

2023-04-06 06:32 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +    private Book save(final ItBookDetailDTO itBookDetailDTO) {
Thật ra thì cái này có save book đâu. Gọi book store để save book từ đây cũng được

2023-04-06 09:52 UTC, tleviet approved these changes

2023-04-06 17:14 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +        bookStore.saveAll(bookList);
Đã save rồi còn save nữa??

2023-04-06 17:15 UTC, voquanghoa commented
Export collection của Postman và add lên, bỏ vào thư mục docs

2023-04-06 17:31 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +        bookStore.saveAll(bookList);
nếu vậy phải bỏ đi hàm saveAll  à a, e thấy bỏ đi vẫn chạy được những lại k tận dụng được việc mình tạo ra bookList kia a

2023-04-06 18:09 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +        bookStore.saveAll(bookList);
resolved, e k save ở bước tạo mới book từ ItBookDetailDTO nữa mà e lưu vào 1 List sau đó mới saveAll 1 thể luôn a

2023-04-06 18:14 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +        bookStore.saveAll(bookList);
Bỏ cái `bookStore.saveAll(bookList);` đi

2023-04-07 02:23 UTC, voquanghoa requested changes

2023-04-07 02:23 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                .toList();
List không được sử dụng

2023-04-07 02:52 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +                .toList();
resolved

2023-04-07 03:55 UTC, nguyenvanman requested changes

2023-04-07 03:55 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +        book.setIsbn13(book.getIsbn13());
không update book truyền vào
```
final var bookToCreate = book.withIsbn13(...).withUserId(..).with...(...);
return bookStore.save(bookToCreate)
```

2023-04-07 03:57 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ItBookService.java
> +    private Book save(final ItBookDetailDTO itBookDetailDTO) {
Trả về void

2023-04-07 03:57 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ScheduledTask.java
> +public class ScheduledTask {
Move class này ra package `jobs` (cùng level với api, domain...)

2023-04-07 03:57 UTC, voquanghoa commented on src/main/java/com/bathanh/apibook/integration/ScheduledTask.java
> +    @Scheduled(fixedRate = 600000)
dùng thêm tham số timeUnit và để fixRate lại số dễ đọc hơn. Ví dụ 6 và HOUR

2023-04-07 04:06 UTC, voquanghoa approved these changes

2023-04-07 04:22 UTC, nguyenhoanganhtuan1206 approved these changes

2023-04-07 04:23 UTC, nguyenhoanganhtuan1206 approved these changes

2023-04-07 04:36 UTC, nguyenvanman requested changes

2023-04-07 04:36 UTC, nguyenvanman commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +    private void verifyIsbn13BookAvailable(final Book book) {
hàm này input là 1 string isbn13 là đủ rồi

2023-04-07 04:41 UTC, hobathanh commented on src/main/java/com/bathanh/apibook/domain/book/BookService.java
> +    private void verifyIsbn13BookAvailable(final Book book) {
resolved

2023-04-07 04:44 UTC, nguyenvanman approved these changes

2023-04-07 04:47 UTC, merged